/**
 * Form Component Generator Skill
 * Generate React Hook Form components with shadcn/ui
 */

import { SkillResult } from '../types/common.js';

interface FormField {
  name: string;
  type: 'text' | 'email' | 'number' | 'select' | 'textarea';
  label: string;
  required: boolean;
  options?: string[];
}

interface FormOptions {
  componentName: string;
  fields: FormField[];
}

export class FormGenerator {
  async generate(options: FormOptions): Promise<SkillResult<string>> {
    try {
      console.log(`🔍 Generating form component: ${options.componentName}...\n`);

      const component = this.generateComponent(options);

      console.log(`✓ Generated ${options.fields.length} form fields`);
      console.log('✓ Added validation with Zod');
      console.log('✓ Integrated React Hook Form\n');

      return {
        success: true,
        data: component,
        suggestions: [
          `Save to: src/components/${options.componentName}.tsx`,
          'Import and use in your page/component',
          'Customize validation rules as needed'
        ]
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  private generateComponent(options: FormOptions): string {
    return `/**
 * ${options.componentName}
 * Generated by Form Generator
 */

'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

// Validation schema
const formSchema = z.object({
${options.fields.map(f => `  ${f.name}: z.string()${f.required ? `.min(1, '${f.label} is required')` : `.optional()`}`).join(',\n')}
});

type FormData = z.infer<typeof formSchema>;

interface ${options.componentName}Props {
  onSubmit: (data: FormData) => Promise<void>;
  onCancel?: () => void;
  defaultValues?: Partial<FormData>;
}

export function ${options.componentName}({
  onSubmit,
  onCancel,
  defaultValues
}: ${options.componentName}Props) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: defaultValues || {
${options.fields.map(f => `      ${f.name}: ''`).join(',\n')}
    }
  });

  const handleSubmit = async (data: FormData) => {
    try {
      setIsSubmitting(true);
      setError(null);
      await onSubmit(data);
      form.reset();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>${options.componentName.replace(/([A-Z])/g, ' $1').trim()}</CardTitle>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
            {error && (
              <div className="text-sm text-red-600 bg-red-50 p-3 rounded">
                {error}
              </div>
            )}

${options.fields.map(f => `            <FormField
              control={form.control}
              name="${f.name}"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>${f.label}</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      type="${f.type === 'number' ? 'number' : 'text'}"
                      disabled={isSubmitting}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />`).join('\n\n')}

            <div className="flex gap-4">
              <Button type="submit" disabled={isSubmitting}>
                {isSubmitting ? 'Submitting...' : 'Submit'}
              </Button>
              {onCancel && (
                <Button type="button" variant="outline" onClick={onCancel}>
                  Cancel
                </Button>
              )}
            </div>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
`;
  }
}

export async function run(args?: string): Promise<void> {
  const generator = new FormGenerator();

  const result = await generator.generate({
    componentName: 'ExampleForm',
    fields: [
      { name: 'name', type: 'text', label: 'Name', required: true },
      { name: 'email', type: 'email', label: 'Email', required: true },
      { name: 'description', type: 'textarea', label: 'Description', required: false }
    ]
  });

  if (result.success && result.data) {
    console.log('\n═══════════════════════════════════════════════════════════════');
    console.log('  FORM GENERATOR');
    console.log('═══════════════════════════════════════════════════════════════\n');

    console.log('Generated Component:\n');
    console.log(result.data);

    console.log('\n💡 Next steps:\n');
    result.suggestions?.forEach(s => console.log(`  ${s}`));

    console.log('\n═══════════════════════════════════════════════════════════════\n');
  } else {
    console.error('❌ Generation failed:', result.error);
    process.exit(1);
  }
}
