import type { DashboardTableColumn } from '@/components/layouts/DashboardColumnCustomizer';

export const COUPON_COLUMNS: DashboardTableColumn[] = [
  {
    key: 'code',
    label: 'Coupon Code',
    sortable: true,
    defaultVisible: true,
    required: true,
    mobileOrder: 1,
    hideOnMobile: false,
    mobileLabel: 'Code',
    className: 'font-mono',
  },
  {
    key: 'name',
    label: 'Name',
    sortable: true,
    defaultVisible: true,
    required: true,
    mobileOrder: 2,
    hideOnMobile: false,
    className: 'min-w-[150px]',
  },
  {
    key: 'description',
    label: 'Description',
    defaultVisible: true,
    mobileOrder: 3,
    hideOnMobile: false,
    className: 'min-w-[200px]',
  },
  {
    key: 'type',
    label: 'Type',
    sortable: true,
    defaultVisible: true,
    mobileOrder: 4,
    hideOnMobile: false,
  },
  {
    key: 'value',
    label: 'Value',
    sortable: true,
    defaultVisible: true,
    mobileOrder: 5,
    hideOnMobile: false,
  },
  {
    key: 'minimumAmount',
    label: 'Min Amount',
    sortable: true,
    defaultVisible: false,
    mobileOrder: 6,
    hideOnMobile: true,
  },
  {
    key: 'currentUses',
    label: 'Uses',
    sortable: true,
    defaultVisible: true,
    mobileOrder: 7,
    hideOnMobile: false,
  },
  {
    key: 'validFrom',
    label: 'Valid From',
    sortable: true,
    defaultVisible: false,
    mobileOrder: 8,
    hideOnMobile: true,
  },
  {
    key: 'validUntil',
    label: 'Valid Until',
    sortable: true,
    defaultVisible: true,
    mobileOrder: 9,
    hideOnMobile: false,
    mobileLabel: 'Expires',
  },
  {
    key: 'status',
    label: 'Status',
    sortable: true,
    defaultVisible: true,
    mobileOrder: 10,
    hideOnMobile: false,
  },
  {
    key: 'createdAt',
    label: 'Created',
    sortable: true,
    defaultVisible: false,
    mobileOrder: 11,
    hideOnMobile: true,
  },
  {
    key: 'updatedAt',
    label: 'Updated',
    sortable: true,
    defaultVisible: false,
    mobileOrder: 12,
    hideOnMobile: true,
  },
];