export enum AuditLogAction {
  // Auth and security actions
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_BLOCKED = 'LOGIN_BLOCKED',
  LOGOUT = 'LOGOUT',
  REGISTRATION = 'REGISTRATION',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_BLACKLISTED = 'SESSION_BLACKLISTED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  INVALID_SESSION = 'INVALID_SESSION',
  ACCOUNT_NOT_APPROVED = 'ACCOUNT_NOT_APPROVED',
  AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',

  // User actions
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  ADMIN_USER_APPROVED = 'ADMIN_USER_APPROVED',
  ADMIN_USER_REJECTED = 'ADMIN_USER_REJECTED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  ACCOUNT_REACTIVATED = 'ACCOUNT_REACTIVATED',

  // Product actions
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  PRODUCT_ARCHIVED = 'PRODUCT_ARCHIVED',
  PRODUCT_UNARCHIVED = 'PRODUCT_UNARCHIVED',
  PRODUCT_RESTORED = 'PRODUCT_RESTORED',

  // Stock actions
  STOCK_ADDITION = 'STOCK_ADDITION',
  STOCK_REMOVAL = 'STOCK_REMOVAL',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  STOCK_RECONCILIATION = 'STOCK_RECONCILIATION',

  // Sales actions
  SALE_CREATED = 'SALE_CREATED',
  SALE_UPDATED = 'SALE_UPDATED',
  SALE_VOIDED = 'SALE_VOIDED',

  // Backup actions
  BACKUP_CREATED = 'BACKUP_CREATED',
  BACKUP_DOWNLOADED = 'BACKUP_DOWNLOADED',

  // Finance-specific actions
  FINANCE_TRANSACTION_CREATED = 'FINANCE_TRANSACTION_CREATED',
  FINANCE_TRANSACTION_UPDATED = 'FINANCE_TRANSACTION_UPDATED',
  FINANCE_TRANSACTION_DELETED = 'FINANCE_TRANSACTION_DELETED',
  FINANCE_TRANSACTION_APPROVED = 'FINANCE_TRANSACTION_APPROVED',
  FINANCE_TRANSACTION_REJECTED = 'FINANCE_TRANSACTION_REJECTED',
  FINANCE_REPORT_GENERATED = 'FINANCE_REPORT_GENERATED',
}

export interface AuditLogEntry {
  id: number;
  userId: number;
  action: AuditLogAction;
  tableName: string;
  recordId: number;
  oldValues: any;
  newValues: any;
  ipAddress?: string;
  userAgent?: string;
  createdAt: Date;
}
