/**
 * Mock Data Factory Skill
 * Generate realistic mock data for testing
 */

import { SkillResult } from '../types/common.js';

export class MockFactory {
  async generate(modelName: string, count: number = 1): Promise<SkillResult<string>> {
    try {
      console.log(`🔍 Generating ${count} mock ${modelName} object(s)...\n`);

      const mocks = this.generateMocks(modelName, count);

      console.log(`✓ Generated ${count} mock ${modelName} object(s)\n`);

      return {
        success: true,
        data: mocks,
        suggestions: [
          'Use in test files for consistent mock data',
          'Extend with more realistic data as needed',
          'Consider using @faker-js/faker for dynamic data'
        ]
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  private generateMocks(modelName: string, count: number): string {
    const mockTemplate = this.getMockTemplate(modelName);

    return `/**
 * Mock ${modelName} factory
 * Generated by Mock Factory
 */

export function create${modelName}Mock(overrides = {}) {
  return {
    ${mockTemplate},
    ...overrides
  };
}

export function create${modelName}Mocks(count = ${count}, overrides = {}) {
  return Array.from({ length: count }, (_, i) => create${modelName}Mock({
    id: i + 1,
    ...overrides
  }));
}

// Example usage:
// const mockProduct = createProductMock({ name: 'Custom Name' });
// const mockProducts = createProductMocks(10);
`;
  }

  private getMockTemplate(modelName: string): string {
    const templates: Record<string, string> = {
      User: `
    id: 1,
    firstName: 'Test',
    lastName: 'User',
    email: 'test@example.com',
    phone: '+2347012345678',
    role: 'STAFF',
    status: 'APPROVED',
    emailVerified: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()`,

      Product: `
    id: 1,
    name: 'Test Product',
    sku: 'SKU-00001',
    description: 'Test product description',
    purchasePrice: 1000,
    sellingPrice: 1500,
    stock: 100,
    categoryId: 1,
    brandId: 1,
    supplierId: 1,
    status: 'ACTIVE',
    createdAt: new Date(),
    updatedAt: new Date()`,

      Category: `
    id: 1,
    name: 'Test Category',
    description: 'Test category description',
    createdAt: new Date(),
    updatedAt: new Date()`,

      Brand: `
    id: 1,
    name: 'Test Brand',
    description: 'Test brand description',
    createdAt: new Date(),
    updatedAt: new Date()`,

      Supplier: `
    id: 1,
    name: 'Test Supplier',
    contactPerson: 'John Doe',
    email: 'supplier@example.com',
    phone: '+2347098765432',
    address: '123 Test St',
    createdAt: new Date(),
    updatedAt: new Date()`
    };

    return templates[modelName] || `
    id: 1,
    name: 'Test ${modelName}',
    createdAt: new Date(),
    updatedAt: new Date()`;
  }
}

export async function run(args?: string): Promise<void> {
  const factory = new MockFactory();
  const modelName = args || 'Product';

  const result = await factory.generate(modelName, 5);

  if (result.success && result.data) {
    console.log('\n═══════════════════════════════════════════════════════════════');
    console.log('  MOCK DATA FACTORY');
    console.log('═══════════════════════════════════════════════════════════════\n');

    console.log(`Generated mock factory for ${modelName}:\n`);
    console.log(result.data);

    console.log('\n💡 Next steps:\n');
    result.suggestions?.forEach(s => console.log(`  ${s}`));

    console.log('\n═══════════════════════════════════════════════════════════════\n');
  } else {
    console.error('❌ Generation failed:', result.error);
    process.exit(1);
  }
}
