#!/bin/bash

echo "🚀 Resend Setup Helper"
echo "======================"
echo ""
echo "📧 To complete your Resend setup:"
echo ""
echo "1. Go to: https://resend.com/api-keys"
echo "2. Log in or create an account"
echo "3. Create a new API key"
echo "4. Copy the API key (starts with 're_')"
echo ""
echo "5. Update your .env.local file:"
echo "   Replace: RESEND_API_KEY=\"re_YOUR_ACTUAL_API_KEY_HERE\""
echo "   With:    RESEND_API_KEY=\"re_xxxxxxxxxxxxxxxxxxxxx\""
echo ""
echo "6. Test your setup:"
echo "   npm run test:resend-config"
echo "   npm run test:resend-email"
echo ""
echo "🔒 Security Notes:"
echo "   - Keep your API key secret"
echo "   - Don't commit it to version control"
echo "   - Test emails will be sent to baawapay+resend-test@gmail.com"
echo ""
echo "📊 Optional Domain Verification:"
echo "   - Go to: https://resend.com/domains"
echo "   - Add and verify 'baawa.com' for better deliverability"
echo "   - This improves email reputation and delivery rates"
echo ""
